valid_location_qualifiers = [{'text': 'oval'},
                             {'text': 'town centre',
                                 'penalty_following_locality': 10},
                             {'text': 'recreation reserve',
                                 'penalty_following_locality': 10},
                             {'text': 'estate'},
                             {'text': 's/centre'},
                             {'text': 'arcade'},
                             {'text': 'centre'},
                             {'text': 'pavilion'},
                             {'text': 'center'},
                             {'text': 'headquarters'},
                             {'text': 'supermarket'},
                             {'text': 'shp\/centre'},
                             {'text': 'park', 'penalty_following_locality': 10},
                             {'text': 'resort'},
                             {'text': 'reserve'},
                             {'text': 'golf course'},
                             {'text': 'golf club'},
                             {'text': 'velodrome'},
                             {'text': 'club house'},
                             {'text': 'hall'},
                             {'text': 'clubrooms'},
                             {'text': 'clubhouse'},
                             {'text': 'association'},
                             {'text': 'education'},
                             {'text': 'chambers'},
                             {'text': 'lodge'},
                             {'text': 'chalet'},
                             {'text': 'house'},
                             {'text': 'village'},
                             {'text': 'college'},
                             {'text': 'showgrounds'},
                             {'text': 'rooms'},
                             {'text': 'plaza'},
                             {'text': 'court'},
                             {'text': 'square'},
                             {'text': 'bridge'},
                             {'text': 'walk'},
                             {'text': 'central'},
                             {'text': 'hub'},
                             {'text': 'office'},
                             {'text': 'restaurant'},
                             {'text': 'valley'},
                             {'text': 'chase'},
                             {'text': 'cafe'},
                             {'text': 'station'},
                             {'text': 's\/centre'},
                             {'text': 'complex'},
                             {'text': 'pavillion'},
                             {'text': 'opposite'},
                             {'text': 'bldg'},
                             {'text': 'stadium'},
                             {'text': 'foreshore'},
                             {'text': 'building'},
                             {'text': 'tower'},
                             {'text': 'yard'},
                             {'text': 'homestead'},
                             {'text': 'marina'},
                             {'text': 'campus'},
                             {'text': 'airport'},
                             {'text': 'store'},
                             {'text': 'gate'},
                             {'text': 'hotel'},
                             {'text': 'club'},
                             {'text': 'raceway'},
                             {'text': 'vaults'},
                             {'text': 'harbour'},
                             {'text': 'gardens'},
                             {'text': 'subdivision'},
                             {'text': 'racing track'},
                             {'text': 'garden'},
                             {'text': 'racecourse'},
                             {'text': 'ballroom'},
                             {'text': 'precinct'},
                             {'text': 'hill'},
                             {'text': 'vineyard'},
                             {'text': 'factory'},
                             {'text': 'grounds'},
                             {'text': 'boathouse'},
                             {'text': 'rooms'},
                             {'text': 'oval'},
                             {'text': 'aerodrome'},
                             {'text': 'beach'},
                             {'text': 'annexe'},
                             {'text': 'shoppingtown'},
                             {'text': 'shopping centre'},
                             {'text': 'zoo'},
                             {'text': 'terrace'},
                             {'text': 'sportsground'},
                             {'text': 'winery'},
                             {'text': 'place'},
                             {'text': 'development'},
                             {'text': 'sqr'},
                             {'text': 'market'},
                             {'text': 'shops'},
                             {'text': 'shop'},
                             {'text': 'mall'},
                             {'text': 'plaza'},
                             {'text': 'square'},
                             {'text': 'promenade'},
                             {'text': 'flats'},
                             {'text': 'res'},
                             {'text': 'sheds'},
                             {'text': 'facility'},
                             {'text': 'school'},
                             {'text': 'ground'},
                             {'text': 'retail'},
                             {'text': 'block'},
                             {'text': 's/c'},
                             {'text': 'river'},
                             {'text': 'theatre'},
                             {'text': 'lake'},
                             {'text': 'fair'},
                             {'text': 'market place'},
                             {'text': 'marketplace'},
                             {'text': 'market'}]

location_qualifier_regexs = [r'^university of [a-z\s]+$']

location_qualifiers_relations = ['opposite', 'beside', 'behind']
